### ISSUE TITLE
Error: Can't find interface/picoprobe.cfg

### ISSUE THREAD

**Issue by Pako2** [maxgerhardt/pio-pico-core-earlephilhower-test#4]
Hi!
Thanks for the great example of how to get started with Pico on PlatformIO. That helped a lot.
I would just like to point out one problem in the current version of the **platformio.ini** file. It is necessary to make an adjustment there.
Instead of
```
debug_tool = picoprobe
upload_protocol = picoprobe
```
you need to use 
```
debug_tool = cmsis-dap
upload_protocol = cmsis-dap

**Comment by maxgerhardt** [comment]
Oh jesus. I really need to delete these one-shot, 3 year old example repositories. The  `platformio.ini` is wrong in multiple places, also the `platform_packages`. Fixed in https://github.com/maxgerhardt/pio-pico-core-earlephilhower-test/commit/6f92ab3b351d1e76294aa01c71c11fc440999b3e.

Please refer to the regular documentation instead. https://arduino-pico.readthedocs.io/en/latest/platformio.html
